version: '3.8'

services:
  operandi-rabbit-mq:
    image: ghcr.io/subugoe/operandi-operandi-rabbitsmq:main
    container_name: operandi-rabbit-mq
    hostname: rabbit-mq-host
    ports:
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
    volumes:
      - ~/.docker-conf/rabbitmq/etc/:/var/etc/rabbitmq/
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq/
    networks:
      - operandi
    healthcheck:
      test: [ "CMD", "nc", "-z", "0.0.0.0", "5672" ]
      interval: 120s
      timeout: 30s
      retries: 5
      
  operandi-mongodb:
    image: "mongo"
    container_name: operandi-mongodb
    ports:
      - "27018:27017"
    volumes:
      - "/tmp/operandi-mongo-data:/data/db"

  operandi-server:
    image: ghcr.io/subugoe/operandi-operandi-server:main
    container_name: operandi-server
    depends_on:
      operandi-rabbit-mq:
        condition: service_healthy
    restart: on-failure
    ports:
      - "8000:8000"
    networks:
      - operandi
    command: operandi-server server start --host 0.0.0.0 --port 8000 --rabbit-mq-host rabbit-mq-host

  operandi-broker:
    image: ghcr.io/subugoe/operandi-operandi-broker:main
    container_name: operandi-broker
    depends_on:
      operandi-rabbit-mq:
        condition: service_healthy
    restart: on-failure
    networks:
      - operandi
    command: operandi-broker broker start --rabbit-mq-host rabbit-mq-host

networks:
  operandi:
    name: operandi
    driver: bridge
    driver_opts:                         
      com.docker.network.driver.mtu: 1450

