version: '3.8'

services:
  operandi-rabbitmq:
    image: "rabbitmq:3.8-management"
    container_name: operandi-rabbitmq
    hostname: rabbit-mq-host
    ports:
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
    volumes:
      - "/rabbitmq-data/etc/:/var/etc/rabbitmq/"
      - "/rabbitmq-data/data/:/var/lib/rabbitmq/"
      - "/rabbitmq-data/log/:/var/log/rabbitmq/"
      - type: bind
        source: ./src/rabbitmq_definitions.json
        target: /rmq_definitions.json
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_management load_definitions "/rmq_definitions.json"
    networks:
      - operandi
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30

  operandi-mongodb:
    image: "mongo"
    container_name: operandi-mongodb
    ports:
      - "27018:27017"
    volumes:
      - "/operandi-mongodb:/data/db"
    networks:
      - operandi

  operandi-server:
    image: ghcr.io/subugoe/operandi-server:main
    container_name: operandi-server
    depends_on:
      operandi-rabbitmq:
        condition: service_healthy
    restart: on-failure
    ports:
      - "80:8000"
    environment:
      - OPERANDI_SERVER_DEFAULT_USERNAME=test
      - OPERANDI_SERVER_DEFAULT_PASSWORD=test
      - OPERANDI_SERVER_BASE_DIR=/tmp/operandi_data
      - OPERANDI_SERVER_URL_LIVE=http://operandi.ocr-d.de
      - OPERANDI_LOGS_DIR=/tmp/operandi_logs
      - OPERANDI_DB_URL=mongodb://172.17.0.1:27018
      - OPERANDI_RABBITMQ_URL=amqp://default-publisher:default-publisher@rabbit-mq-host:5672
    volumes:
      - "/tmp/operandi_logs/:/tmp/operandi_logs/"
      - "/tmp/operandi_data/:/tmp/operandi_data/"
      - "/tmp/operandi_data_tests/:/tmp/operandi_data_tests/"
      - "/tmp/operandi_logs_tests/:/tmp/operandi_logs_tests/"
    networks:
      - operandi
    command: operandi-server start --host 0.0.0.0 --port 8000

  operandi-broker:
    image: ghcr.io/subugoe/operandi-broker:main
    container_name: operandi-broker
    depends_on:
      operandi-rabbitmq:
        condition: service_healthy
    restart: on-failure
    environment:
      - OPERANDI_HPC_SSH_KEYPATH=/home/root/.ssh/gwdg-cluster
      - OPERANDI_LOGS_DIR=/tmp/operandi_logs
      - OPERANDI_DB_URL=mongodb://172.17.0.1:27018
      - OPERANDI_RABBITMQ_URL=amqp://default-consumer:default-consumer@rabbit-mq-host:5672
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/tmp/operandi_logs/:/tmp/operandi_logs/"
      - "/tmp/operandi_data/:/tmp/operandi_data/"
      - "/tmp/operandi_data_tests/:/tmp/operandi_data_tests/"
      - "/tmp/operandi_logs_tests/:/tmp/operandi_logs_tests/"
      - "/home/mm/.ssh/gwdg-cluster:/home/root/.ssh/gwdg-cluster"
    networks:
      - operandi
    command: operandi-broker start

networks:
  operandi:
    name: operandi
    driver: bridge
    driver_opts:                         
      com.docker.network.driver.mtu: 1450
