version: '3.8'

services:
  operandi-rabbit-mq:
    image: "rabbitmq:3-management"
    container_name: operandi-rabbitmq
    hostname: rabbit-mq-host
    ports:
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
    volumes:
      - "/rabbitmq-data/etc/:/var/etc/rabbitmq/"
      - "/rabbitmq-data/data/:/var/lib/rabbitmq/"
      - "/rabbitmq-data/log/:/var/log/rabbitmq/"
      - type: bind
        source: /home/cloud/repos/operandi/src/definitions.json
        target: /rmq_definitions.json
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_management load_definitions "/rmq_definitions.json"
    networks:
      - operandi
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30

  operandi-mongodb:
    image: "mongo"
    container_name: operandi-mongodb
    ports:
      - "27018:27017"
    volumes:
      - "/operandi-mongodb:/data/db"
    networks:
      - operandi

  operandi-server:
    image: ghcr.io/subugoe/operandi-operandi-server:main
    container_name: operandi-server
    depends_on:
      operandi-rabbitmq:
        condition: service_healthy
    restart: on-failure
    ports:
      - "80:8000"
    environment:
      - OCRD_WEBAPI_BASE_DIR=/operandi-data
      - OCRD_WEBAPI_DB_URL=mongodb://172.17.0.1:27018
      - OPERANDI_LOGS_DIR=/operandi-logs
    volumes:
      - "/operandi-logs/:/operandi-logs/"
      - "/operandi-data/:/operandi-data/"
      - "~/venv37-ocrd/:/root/venv37-ocrd/"
    networks:
      - operandi
    command: operandi-server start --host 0.0.0.0 --port 8000 --db-url mongodb://172.17.0.1:27018 --rmq-host rabbit-mq-host --rmq-port 5672

  operandi-broker:
    image: ghcr.io/subugoe/operandi-operandi-broker:main
    container_name: operandi-broker
    depends_on:
      operandi-rabbitmq:
        condition: service_healthy
    restart: on-failure
    environment:
      - OPERANDI_LOGS_DIR=/usr/operandi-logs
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/operandi-logs/:/operandi-logs/"
      - "/operandi-data/:/operandi-data/"
      - "~/venv37-ocrd/:/root/venv37-ocrd/"
    networks:
      - operandi
    command: operandi-broker start --db-url mongodb://172.17.0.1:27018 --rmq-host rabbit-mq-host --rmq-port 5672

networks:
  operandi:
    name: operandi
    driver: bridge
    driver_opts:                         
      com.docker.network.driver.mtu: 1450
