version: '3.8'

services:
  operandi-rabbitmq:
    image: "rabbitmq:3.8-management"
    container_name: operandi-rabbitmq
    hostname: rabbit-mq-host
    ports:
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
    volumes:
      - "/rabbitmq-data/etc/:/var/etc/rabbitmq/"
      - "/rabbitmq-data/data/:/var/lib/rabbitmq/"
      - "/rabbitmq-data/log/:/var/log/rabbitmq/"
      - type: bind
        source: ./src/rabbitmq_definitions.json
        target: /rmq_definitions.json
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_management load_definitions "/rmq_definitions.json"
    networks:
      - operandi
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30

  operandi-mongodb:
    image: "mongo"
    container_name: operandi-mongodb
    ports:
      - "27018:27017"
    volumes:
      - "/operandi-mongodb:/data/db"
    networks:
      - operandi

  operandi-server:
    image: operandi-server
    container_name: operandi-server
    build:
      context: ./src
      dockerfile: ./Dockerfile_server  
    depends_on:
      operandi-rabbitmq:
        condition: service_healthy
    restart: on-failure
    ports:
      - "80:8000"
    environment:
      - OCRD_WEBAPI_BASE_DIR=/operandi-data
      - OCRD_WEBAPI_DB_URL=mongodb://172.17.0.1:27018
      - OCRD_WEBAPI_SERVER_PATH=http://operandi.ocr-d.de
      - OPERANDI_LIVE_SERVER_URL=http://operandi.ocr-d.de
      - OPERANDI_LOGS_DIR=/operandi-logs
      - OPERANDI_URL_DB=mongodb://172.17.0.1:27018
      - OPERANDI_URL_RABBITMQ_SERVER=rabbit-mq-host:5672
    volumes:
      - "/operandi-data/:/operandi-data/"
      - "/operandi-logs/:/operandi-logs/"
      - "~/venv37-ocrd/:/root/venv37-ocrd/"
    networks:
      - operandi
    command: operandi-server start --host 0.0.0.0 --port 8000

  operandi-broker:
    image: operandi-broker
    container_name: operandi-broker
    build:
      context: ./src
      dockerfile: ./Dockerfile_broker
    depends_on:
      operandi-rabbitmq:
        condition: service_healthy
    restart: on-failure
    environment:
      - OPERANDI_LOGS_DIR=/operandi-logs
      - OPERANDI_URL_DB=mongodb://172.17.0.1:27018
      - OPERANDI_URL_RABBITMQ_SERVER=rabbit-mq-host:5672
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/operandi-logs/:/operandi-logs/"
      - "/operandi-data/:/operandi-data/"
      - "~/venv37-ocrd/:/root/venv37-ocrd/"
    networks:
      - operandi
    command: operandi-broker start

networks:
  operandi:
    name: operandi
    driver: bridge
    driver_opts:                         
      com.docker.network.driver.mtu: 1450
