version: '3.8'

services:
  operandi-rabbit-mq:
    image: ghcr.io/subugoe/operandi-operandi-rabbitsmq:main
    container_name: operandi-rabbit-mq
    hostname: rabbit-mq-host
    ports:
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
    volumes:
      - "~/.docker-conf/rabbitmq/etc/:/var/etc/rabbitmq/"
      - "~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/"
      - "~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq/"
    networks:
      - operandi
    healthcheck:
      test: [ "CMD", "nc", "-z", "0.0.0.0", "5672" ]
      interval: 10s
      timeout: 10s
      retries: 15

  operandi-mongodb:
    image: "mongo"
    container_name: operandi-mongodb
    ports:
      - "27018:27017"
    volumes:
      - "/operandi-mongodb:/data/db"
    networks:
      - operandi

  operandi-server:
    image: ghcr.io/subugoe/operandi-operandi-server:main
    container_name: operandi-server
    depends_on:
      operandi-rabbit-mq:
        condition: service_healthy
    restart: on-failure
    ports:
      - "80:8000"
    environment:
      - OCRD_WEBAPI_BASE_DIR=/operandi-data
      - OCRD_WEBAPI_DB_URL=mongodb://172.17.0.1:27018
      - OPERANDI_LOGS_DIR=/operandi-logs
    volumes:
      - "/operandi-logs/:/operandi-logs/"
      - "/operandi-data/:/operandi-data/"
      - "~/venv37-ocrd/:/root/venv37-ocrd/"
    networks:
      - operandi
    command: operandi-server start --host 0.0.0.0 --port 8000 --db-url mongodb://172.17.0.1:27018 --rmq-host rabbit-mq-host --rmq-port 5672

  operandi-broker:
    image: ghcr.io/subugoe/operandi-operandi-broker:main
    container_name: operandi-broker
    depends_on:
      operandi-rabbit-mq:
        condition: service_healthy
    restart: on-failure
    environment:
      - OPERANDI_LOGS_DIR=/usr/operandi-logs
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/operandi-logs/:/operandi-logs/"
      - "/operandi-data/:/operandi-data/"
      - "~/venv37-ocrd/:/root/venv37-ocrd/"
    networks:
      - operandi
    command: operandi-broker start --db-url mongodb://172.17.0.1:27018 --rmq-host rabbit-mq-host --rmq-port 5672

networks:
  operandi:
    name: operandi
    driver: bridge
    driver_opts:                         
      com.docker.network.driver.mtu: 1450
