# "rabbit-mq-host" when Dockerized
# check the docker-compose.yml file
rabbit_mq_host = "localhost"

# This is the default port on which the RabbitMQ instance
# is running after installation, do not change it unless you know how to configure it properly.
# Pika Python client must use the same port to be able to communicate with the RabbitMQ
rabbit_mq_port = 5672

default_exchange_name = "operandi_exchanger"
default_exchange_type = "direct"
default_queue_server_to_broker = "operandi-server-to-broker"
default_queue_harvester_to_broker = "operandi-harvester-to-broker"

# NOTE
# Make sure RabbitMQ is enabled and running on 5672 and 25672:
# $ sudo lsof -i -P -n | grep LISTEN

# if not running - enable and start it:
# $ sudo systemctl enable rabbitmq-server
# $ sudo systemctl start rabbitmq-server

# If the rabbitmq management is not running on port 15672
# Enable it:
# sudo rabbitmq-plugins enable rabbitmq_management

# For more advanced networking options:
# check here: https://www.rabbitmq.com/configure.html
# check here: https://www.rabbitmq.com/networking.html
